# Generated by Django 3.2.5 on 2021-07-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='generators/', verbose_name='Файл генератора')),
                ('dataset_size', models.IntegerField(verbose_name='Размер датасета')),
                ('num_grams', models.IntegerField(default=2, verbose_name='Размер n-грам')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст юморески')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('generator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jokes.generators')),
            ],
        ),
    ]
