# Generated by Django 3.2.5 on 2021-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generators',
            options={'verbose_name': 'Генератор', 'verbose_name_plural': 'Генераторы'},
        ),
        migrations.AlterModelOptions(
            name='jokes',
            options={'verbose_name': 'Юмореска', 'verbose_name_plural': 'Юморески'},
        ),
        migrations.AlterField(
            model_name='generators',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл генератора'),
        ),
    ]
