# Generated by Django 3.2.5 on 2021-07-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20210723_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='generator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jokes.generators', verbose_name='Генератор'),
        ),
    ]
