# Generated by Django 3.2.5 on 2021-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_alter_jokes_generator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generators',
            name='file',
            field=models.FileField(upload_to='./jokes/GeneratorModule/pretrained/', verbose_name='Файл генератора'),
        ),
    ]
