# Generated by Django 3.2.5 on 2021-07-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_alter_generators_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jokes',
            old_name='generator_id',
            new_name='generator',
        ),
    ]
