# Generated by Django 3.2.5 on 2021-07-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_rename_generator_id_jokes_generator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generators',
            old_name='data',
            new_name='date',
        ),
    ]
