# Generated by Django 3.2.5 on 2021-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_rename_data_generators_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='generators',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Описание модели'),
        ),
    ]
